server:
  port: 8000

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##NURSINGHOME_DETECTION
    password: NURSINGHOME_DETECTION
    url: jdbc:oracle:thin:@localhost:1521:xe

mybatis:
  mapper-locations: mappers/**/*.xml
